### PR TITLE
Switch to JOSESwift upstream version >=0.3.0

### PR DESCRIPTION
**Pull request by srosenda**
# Description of change

Change JOSESwift dependency from forked https://github.com/niscy-eudiw/JOSESwift.git to the upstream https://github.com/airsidemobile/JOSESwift.git v0.3.0 or later minor version.

## Type of change

Dependency update and switch back to upstream version.

# How Has This Been Tested?

- [X] Automated test suite of the project passes. I am not completely sure that the suite has relevant coverage to verify this change and would require input from the maintainers to validate this.

# Checklist:

- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the readme
- [X] My changes generate no new warnings
- [ ] I have added unit tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by dtsiflit — APPROVED** [review]

**Comment by dtsiflit** [comment]
Thanks for this @srosenda we tested it on our end and all is good. We have also updated the openid4vp library to use this.

**Comment by dtsiflit** [comment]
Addresses #78

**Comment by srosenda** [comment]
> Thanks for this @srosenda we tested it on our end and all is good. We have also updated the openid4vp library to use this.

Great, thanks @dtsiflit!

**Comment by daniel-moh** [comment]
👏 Good work guys. 

I'm one of the maintainers of JOSESwift. We've been loosely following your work on the EUDI project with interest and we are glad our little project is helpful. If there's ever something you need, feel free to open an issue over at JOSESwift and tag me. I'll make sure it gets addressed with priority.

**Comment by dtsiflit** [comment]
> 👏 Good work everyone.
> 
> I'm one of the maintainers of JOSESwift. We've been loosely following your work on the EUDI project with interest and we are glad our little project is helpful. If there's ever something you need, feel free to open an issue over at JOSESwift and tag me. I'll make sure it gets addressed with priority.

Thank you very much, @daniel-moh ! We are also glad to have come across JOSESwift all those months ago.

**Pull request merged**
